version: 0.2

phases:
  install:
    commands:
      - echo "Checking if Docker is installed..."
      - docker --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_REGION:-ap-southeast-2} | docker login --username AWS --password-stdin 597088035727.dkr.ecr.ap-southeast-2.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build --no-cache --progress=plain -t lineage-web-ui -f Dockerfile .
      - docker tag lineage-web-ui:latest 597088035727.dkr.ecr.ap-southeast-2.amazonaws.com/lineage-web-ui:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 597088035727.dkr.ecr.ap-southeast-2.amazonaws.com/lineage-web-ui:latest